// <auto-generated />
namespace RentApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class comment12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comment12));
        
        string IMigrationMetadata.Id
        {
            get { return "201808131650174_comment12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
