// <auto-generated />
namespace RentApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class listaustringslikakodvozila : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listaustringslikakodvozila));
        
        string IMigrationMetadata.Id
        {
            get { return "201806210726162_lista u string slika kod vozila"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
