// <auto-generated />
namespace RentApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Imagesisnotworking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Imagesisnotworking));
        
        string IMigrationMetadata.Id
        {
            get { return "201806191306254_Images is not working"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
